// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	"github.com/dhoelle/redactr"
)

type TokenUnredacter struct {
	UnredactTokensStub        func(string, ...redactr.UnredactTokensOption) (string, error)
	unredactTokensMutex       sync.RWMutex
	unredactTokensArgsForCall []struct {
		arg1 string
		arg2 []redactr.UnredactTokensOption
	}
	unredactTokensReturns struct {
		result1 string
		result2 error
	}
	unredactTokensReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *TokenUnredacter) UnredactTokens(arg1 string, arg2 ...redactr.UnredactTokensOption) (string, error) {
	fake.unredactTokensMutex.Lock()
	ret, specificReturn := fake.unredactTokensReturnsOnCall[len(fake.unredactTokensArgsForCall)]
	fake.unredactTokensArgsForCall = append(fake.unredactTokensArgsForCall, struct {
		arg1 string
		arg2 []redactr.UnredactTokensOption
	}{arg1, arg2})
	fake.recordInvocation("UnredactTokens", []interface{}{arg1, arg2})
	fake.unredactTokensMutex.Unlock()
	if fake.UnredactTokensStub != nil {
		return fake.UnredactTokensStub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.unredactTokensReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *TokenUnredacter) UnredactTokensCallCount() int {
	fake.unredactTokensMutex.RLock()
	defer fake.unredactTokensMutex.RUnlock()
	return len(fake.unredactTokensArgsForCall)
}

func (fake *TokenUnredacter) UnredactTokensCalls(stub func(string, ...redactr.UnredactTokensOption) (string, error)) {
	fake.unredactTokensMutex.Lock()
	defer fake.unredactTokensMutex.Unlock()
	fake.UnredactTokensStub = stub
}

func (fake *TokenUnredacter) UnredactTokensArgsForCall(i int) (string, []redactr.UnredactTokensOption) {
	fake.unredactTokensMutex.RLock()
	defer fake.unredactTokensMutex.RUnlock()
	argsForCall := fake.unredactTokensArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *TokenUnredacter) UnredactTokensReturns(result1 string, result2 error) {
	fake.unredactTokensMutex.Lock()
	defer fake.unredactTokensMutex.Unlock()
	fake.UnredactTokensStub = nil
	fake.unredactTokensReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *TokenUnredacter) UnredactTokensReturnsOnCall(i int, result1 string, result2 error) {
	fake.unredactTokensMutex.Lock()
	defer fake.unredactTokensMutex.Unlock()
	fake.UnredactTokensStub = nil
	if fake.unredactTokensReturnsOnCall == nil {
		fake.unredactTokensReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.unredactTokensReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *TokenUnredacter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.unredactTokensMutex.RLock()
	defer fake.unredactTokensMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *TokenUnredacter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ redactr.TokenUnredacter = new(TokenUnredacter)
